version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile-frontend
    ports:
      - '80:80'
    environment:
      - REACT_APP_API_URL=http://backend:3500

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile-backend
    ports:
      - "3500:3500"
    environment:
      - PORT=5000
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"